name: Invalidate CloudFront Cache
description: Github action to invalidate cache from cloudfront

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: cloudbeds/workflows/.github/actions/configure-aws@main
      with:
        role-to-assume: ${{ env.AWS_ARN }}

    - name: Invalidate CloudFront cache
      shell: bash
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DISTRIBUTION_ID }} \
          --paths "${{ env.CLOUDFRONT_PATH }}/*"
