name: NPM Install and Code Lint
description: Eslint code linter

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - uses: cloudbeds/workflows/.github/actions/npm-install@main

    - name: Lint
      shell: bash
      run: |
        npm run lint --if-present
        npm run lint:ts --if-present
