name: NPM Install and Code Lint
description: Eslint code linter

inputs:
  envVars:
    description: List of environment variables to set up, given in VAR=value format.
    required: false
    default: ''
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    required: false
    default: ''
  npmArgs:
    description: Additional arguments to pass to NPM
    default: ''
    required: false    

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - uses: cloudbeds/workflows/.github/actions/npm-install@main
      with:
        useNpmCI: false
        npmArgs: ${{ inputs.npmArgs }}

    - name: Lint
      shell: bash
      run: |
        for envVar in "${{ inputs.envVars }}"; do
          if [[ -n "$envVar" ]]; then export $envVar; fi
        done

        npm run download-types --if-present
        # deprecated
        npm run downloadTypes --if-present

        npm run lint --if-present
        npm run lint:ts --if-present
