name: NPM Install and Code Lint
description: Eslint code linter

inputs:
  envVars:
    description: List of environment variables to set up, given in VAR=value format.
    required: false
    default: ''
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        ref: ${{ inputs.ref }}

    - uses: cloudbeds/workflows/.github/actions/npm-install@main
      with:
        useNpmCI: false

    - name: Lint
      shell: bash
      run: |
        for envVar in "${{ inputs.envVars }}"; do
          if [[ -n "$envVar" ]]; then export $envVar; fi
        done

        npm run download-types --if-present
        # deprecated
        npm run downloadTypes --if-present

        npm run lint --if-present
        npm run lint:ts --if-present
