name: NPM Install and Code Lint
description: Eslint code linter

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - name: Initialize npm cache
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install dependencies
      shell: bash
      run: |
        if [[ -n $NPM_TOKEN ]]; echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc; fi
        export HUSKY=0
        npm config set audit=false fund=false
        npm ci

    - name: Lint
      shell: bash
      run: |
        npm run lint --if-present
        npm run lint:ts --if-present
