name: Get version from package.json
description: Returns version number from package.json

inputs:
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    default: ''
    required: false

outputs:
  appVersion:
    description: App version
    value: ${{ steps.package-json-version.outputs.current-version }}

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        ref: ${{ inputs.ref }}

    - name: Get Version from package.json
      id: package-json-version
      # https://github.com/martinbeentjes/npm-get-version-action v1.2.3
      uses: martinbeentjes/npm-get-version-action@7aa1d82604bb2dbe377a64ca35e692e6fe333c9c
