name: Get version from package.json
description: Returns version number from package.json

inputs:
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    default: ''
    required: false

outputs:
  appVersion:
    description: App version
    value: ${{ steps.package-json-version.outputs.VERSION }}

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        ref: ${{ inputs.ref }}

    - name: Get Version from package.json
      id: package-json-version
      shell: bash
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
