name: End-to-end Tests
description: Action to run the full suite of end-to-end tests

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize npm cache
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install dependencies
      shell: bash
      run: |
        npm config set audit=false fund=false
        npm ci

    - name: End-to-end tests
      shell: bash
      run: npm run test:e2e
