name: Unit Tests
description: Action to run the full suite of unit tests

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - name: Initialize npm cache
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install dependencies
      shell: bash
      run: |
        npm config set audit=false fund=false
        npm ci

    - name: Unit tests
      shell: bash
      run: npm run test:unit
