name: Code Lint
description: Eslint code linter

inputs:
  install:
    description: Name of the uploaded build artifact
    required: true
  artifactPath:
    description: Destination path for the downloaded build artifact
    default: dist
    required: false
  AWS_ARN:
    description: AWS Amazon Resource Number
    required: true
  S3_URL:
    description: URL to an S3 bucket folder
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npm run lint --if-present
        npm run lint:ts --if-present
