name: NPM Install and Test
description: Action to run the full suite of tests

inputs:
  envVars:
    description: List of environment variables to set up, given in VAR=value format.
    required: false
    default: ''
  withoutCoverage:
    description: Do not run coverage report
    required: false
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        ref: ${{ inputs.ref }}

    - uses: cloudbeds/workflows/.github/actions/npm-install@main

    - name: Test
      shell: bash
      run: |
        for envVar in "${{ inputs.envVars }}"; do
          if [[ -n "$envVar" ]]; then export $envVar; fi
        done

        npm run download-types --if-present
        if [[ $(jq '.scripts["test:coverage:ci"]' < package.json;) != null && "${{ inputs.withoutCoverage }}" != 'true' ]]; then
          npm run test:coverage:ci
          echo "INCLUDE_COVERAGE_REPORT=true" >> $GITHUB_OUTPUT
        else
          npm run test --if-present
        fi
