name: NPM Install and Test
description: Action to run the full suite of tests

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - uses: cloudbeds/workflows/.github/actions/npm-install@main

    - name: Test
      shell: bash
      run: npm test --if-present
