# Generic action to lint, build and test a repo
# In this action the build step happens before testing
# Required for workflows where remote entry types are downloaded within the webpack build
name: Build and Test
description: Build, Lint and Test

inputs:
  artifactName:
    description: Name of the build artifact
    default: build-artifact
    required: false
  artifactPath:
    description: Destination path for the downloaded build artifact
    default: dist
    required: false
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    default: ''
    required: false
  NPM_TOKEN:
    description: NPM token to authenticate with NPM registry
    required: true
  BUILD_ENV_VARS:
    description: Environment variables to pass to the build step
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      # https://github.com/actions/checkout v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        ref: ${{ inputs.ref }}

    - name: Initialize npm cache
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install dependencies
      shell: bash
      run: |
        NPM_TOKEN=${{ inputs.NPM_TOKEN }}
        npm config set audit=false fund=false
        npm ci

    - name: Build
      shell: bash
      run: ${{ inputs.BUILD_ENV_VARS }} npm run build

    # In this workflow testing should happen after Build step
    # e.g. for case when remote types are downloaded with webpack
    - name: Lint
      shell: bash
      run: |
        npm run lint --if-present
        npm run lint:ts --if-present

    - name: Test
      shell: bash
      run: npm test --if-present

    - name: Get version number from package.json
      id: version-from-package-json
      uses: cloudbeds/workflows/.github/actions/get-version-from-package-json@main

    - name: Write build info
      shell: bash
      run: |
        SHA=$(git rev-parse HEAD)
        SHA_SHORT=$(git rev-parse --short HEAD)
        echo "{
          \"sha\": \"$SHA\",
          \"shaShort\": \"$SHA_SHORT\",
          \"version\": \"${{ steps.version-from-package-json.outputs.appVersion }}\",
          \"viewAction\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\",
          \"viewRepo\": \"https://github.com/${{ github.repository }}/tree/$SHA\",
          \"viewCommitHistory\": \"https://github.com/${{ github.repository }}/commits/$SHA\",
          \"viewLastCommit\": \"https://github.com/${{ github.repository }}/commit/$SHA\"
        }" > ${{ inputs.artifactPath }}/build-info.json

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifactName }}
        path: ${{ inputs.artifactPath }}
