name: Semantic Release
description: Release

inputs:
  artifactName:
    description: Name of the uploaded build artifact
    default: build-artifact
    required: false
  artifactPath:
    description: Destination path for the downloaded build artifact
    default: dist
    required: false
  withoutBuiltArtifact:
    description: Indicates that no artifact should be downloaded
    required: false
  publishToNpm:
    description: Enable this to publish artifacts to NPM
    required: false
  GITHUB_TOKEN:
    description: Secret Cloudbeds Github token with write permission
    required: true
  NPM_TOKEN:
    description: Secret NPM token
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.GITHUB_TOKEN }}

    - name: Artifact Path
      shell: bash
      run: echo ${{ inputs.artifactPath }}/${{ inputs.artifactName }}

    - if: inputs.withoutBuiltArtifact =='true'
      name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifactName }}
        path: ${{ inputs.artifactPath }}

    - name: Create config file for Semantic Release
      shell: bash
      run: |
        cat << EOF > .releaserc
        {
          "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/changelog",
            ${{inputs.publishToNpm && '"@semantic-release/npm",' || ''}}
            "@semantic-release/github",
            "@semantic-release/git"
          ]
        }
        EOF

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        branch: main
        semantic_version: 18
        extra_plugins: |
          @semantic-release/changelog@6
          @semantic-release/git@10
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
