name: Add NPM token
description: Adds NPM token to .npmrc

runs:
  using: composite
  steps:
    - shell: bash
      run:
        if [[ -n $NPM_TOKEN && ! -f .npmrc ]];
          then echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc;
        fi
