name: NPM Install and Build
description: Github action to build node projects

inputs:
  npmScript:
    description: Custom build script name
    default: build
    required: false
  envVars:
    description: List of environment variables to set up, given in VAR=value format.
    required: false
    default: ''
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    required: false
    default: ''
  GITHUB_TOKEN:
    description: Secret Cloudbeds Github token with write permission
    required: false
    default: ''
  npmArgs:
    description: Additional arguments to pass to NPM
    default: ''
    required: false    

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.GITHUB_TOKEN || github.token }}

    - uses: cloudbeds/workflows/.github/actions/npm-install@main
      with:
        useNpmCI: false
        npmArgs: ${{ inputs.npmArgs }}

    - name: Build
      shell: bash
      run: |
        for envVar in "${{ inputs.envVars }}"; do
          if [[ -n "$envVar" ]]; then export $envVar; fi
        done

        npm run ${{ inputs.npmScript }}
