name: NPM Install and Build
description: Github action to build node projects

inputs:
  artifactName:
    description: Name of the uploaded build artifact
    default: build-artifact
    required: false
  artifactPath:
    description: Destination path for the downloaded build artifact
    default: dist
    required: false
  npmScript:
    description: Custom build script name
    default: build
    required: false
  withoutBuiltArtifact:
    description: Skip uploading the build artifact
    required: false
  envVars:
    description: List of environment variables to set up, given in VAR=value format.
    required: false
    default: ''
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}

    - uses: cloudbeds/workflows/.github/actions/npm-install@main
      with:
        useNpmCI: false

    - name: Build
      shell: bash
      run: |
        for envVar in "${{ inputs.envVars }}"; do
          if [[ -n "$envVar" ]]; then export $envVar; fi
        done

        npm run ${{ inputs.npmScript }}

    - uses: actions/upload-artifact@v3
      if: inputs.withoutBuiltArtifact != 'true'
      with:
        name: ${{ inputs.artifactName }}
        path: ${{ inputs.artifactPath }}
        if-no-files-found: error
