name: NPM Install and Build
description: Github action to build node projects

inputs:
  npmScript:
    description: Custom build script name
    default: build
    required: false
  envVars:
    description: List of environment variables to set up, given in VAR=value format.
    required: false
    default: ''
  ref:
    description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - uses: cloudbeds/workflows/.github/actions/npm-install@main
      with:
        useNpmCI: false

    - name: Build
      shell: bash
      run: |
        for envVar in "${{ inputs.envVars }}"; do
          if [[ -n "$envVar" ]]; then export $envVar; fi
        done

        npm run ${{ inputs.npmScript }}
