# Generic workflow for a push or pull_request event

name: Lint and Test

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: x2-4core
    steps:
      - name: Lint
        uses: cloudbeds/workflows/.github/actions/npm-install-lint@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Test
    runs-on: x8-core
    steps:
      - uses: actions/checkout@v3
      - uses: cloudbeds/workflows/.github/actions/npm-install@main

      - name: Test
        id: test
        run: |
          if [[ $(jq '.scripts["test:coverage:ci"]' < package.json;) != null ]]; then
            npm run test:coverage:ci
            echo "INCLUDE_COVERAGE_REPORT=true" >> $GITHUB_OUTPUT
          else
            npm run test --if-present
          fi

      - name: Find Current Pull Request
        if: steps.test.outputs.INCLUDE_COVERAGE_REPORT == 'true'
        id: findPr
        uses: jwalton/gh-find-current-pr@v1.3.2

      - name: Report Test Coverage
        if: steps.test.outputs.INCLUDE_COVERAGE_REPORT == 'true'
        uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
          annotations: coverage
          coverage-file: report.json
          base-coverage-file: report.json

