# Generic workflow for a push event
# It should be used for all branches except `main` which should use the `*-release` workflow

name: Lint and Build

on:
  workflow_call:
    inputs:
      runnerForBuild:
        description: The type of runner to use
        required: false
        default: x8-core
        type: string
      artifactName:
        description: Name of the uploaded build artifact
        required: false
        type: string
      artifactPath:
        description: Destination path for the downloaded build artifact
        required: false
        default: dist
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: x2-4core
    steps:
      - name: Lint
        uses: cloudbeds/workflows/.github/actions/npm-install-lint@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build
    runs-on: ${{ inputs.runnerForBuild }}
    steps:
      - name: Build
        uses: cloudbeds/workflows/.github/actions/npm-install-build@main
        with:
          artifactName: ${{ inputs.artifactName }}
          artifactPath: ${{ inputs.artifactPath }}
          withoutBuiltArtifact: ${{ !inputs.artifactName && 'true' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
