# Generic action to lint, build and test a repo
# In this action the build step happens before testing
# Required for workflows where remote entry types are downloaded within the webpack build
name: Build and Test

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: The type of runner to use
        required: false
        default: ubuntu-latest
        type: string
      artifactName:
        description: Name of the build artifact
        required: false
        default: build-artifact
        type: string
      artifactPath:
        description: Destination path for the downloaded build artifact
        required: false
        default: dist
        type: string
      jobName:
        description: Custom job name
        required: false
        default: Build, Lint, Test
        type: string
      ref:
        description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
        required: false
        default: ''
        type: string
      envVars:
        description: List of environment variables to set up, given in VAR=value format.
        required: false
        default: ''
        type: string
      testCoverageAnnotations:
        description: Annotation type for test coverage should be 'all', 'none', 'coverage' or 'failed-tests'
        required: false
        default: coverage
        type: string
      writeBuildInfo:
        description: Whether to write build info to a file
        required: false
        default: true
        type: string
      buildOnly:
        description: Whether to only build the project without lint and test
        required: false
        default: false
        type: string

    outputs:
      appVersion:
        description: App version from package.json
        value: ${{ jobs.build-and-test.outputs.appVersion }}

jobs:
  build-and-test:
    name: ${{ inputs.jobName }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      appVersion: ${{ steps.version-from-package-json.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: cloudbeds/workflows/.github/actions/npm-install@main

      - name: Build
        run: |
          for envVar in "${{ inputs.envVars }}"; do
            if [[ -n "$envVar" ]]; then export $envVar; fi
          done
          npm run build

      # In this workflow testing should happen after Build step
      # e.g. for case when remote types are downloaded with webpack
      - name: Lint
        if: inputs.buildOnly != 'true'
        run: |
          npm run lint --if-present
          npm run lint:ts --if-present

      # Runs tests with coverage when available, otherwise just runs tests
      - name: Test
        id: test
        if: inputs.buildOnly != 'true'
        run: |
          if [[ $(jq '.scripts["test:coverage:ci"]' < package.json;) != null ]]; then
            npm run test:coverage:ci
            echo "INCLUDE_COVERAGE_REPORT=true" >> $GITHUB_ENV
          else
            npm run test --if-present
          fi

      - name: Find Current Pull Request
        if: env.INCLUDE_COVERAGE_REPORT == 'true'
        id: findPr
        uses: jwalton/gh-find-current-pr@v1.3.3

      - name: Report Test Coverage
        if: env.INCLUDE_COVERAGE_REPORT == 'true'
        uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
          annotations: ${{ inputs.testCoverageAnnotations }}
          coverage-file: report.json
          base-coverage-file: report.json

      - id: version-from-package-json
        shell: bash
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: cloudbeds/workflows/.github/actions/write-build-info@main
        if: inputs.writeBuildInfo == 'true'
        with:
          artifactPath: ${{ inputs.artifactPath }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
