# Generic workflow for a push or pull_request event

name: Lint and Test

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: The type of runner to use for test job
        required: false
        default: ubuntu-latest
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: cloudbeds/workflows/.github/actions/npm-install-lint@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: Test
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cloudbeds/workflows/.github/actions/npm-install@main

      - name: Test
        id: test
        run: |
          if [[ $(jq '.scripts["test:coverage:ci"]' < package.json;) != null ]]; then
            npm run test:coverage:ci
            echo "INCLUDE_COVERAGE_REPORT=true" >> $GITHUB_ENV
          else
            npm run test --if-present
          fi

      - name: Find Current Pull Request
        if: env.INCLUDE_COVERAGE_REPORT == 'true'
        id: findPr
        uses: jwalton/gh-find-current-pr@v1.3.3

      - name: Report Test Coverage
        if: env.INCLUDE_COVERAGE_REPORT == 'true'
        uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
          annotations: coverage
          coverage-file: report.json
          base-coverage-file: report.json
