# Generic action to lint, build and test a repo
# In this action the build step happens before testing
# Required for workflows where remote entry types are downloaded within the webpack build
name: Build and Test

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      artifactName:
        description: Name of the build artifact
        default: build-artifact
        required: false
        type: string
      artifactPath:
        description: Destination path for the downloaded build artifact
        default: dist
        required: false
        type: string
      jobName:
        description: Custom job name
        default: Build, Lint, Test
        required: false
        type: string
      ref:
        description: The branch, tag or SHA to checkout. Defaults to the SHA for the event that triggered the workflow.
        default: ''
        required: false
        type: string
      envVars:
        description: List of environment variables to set up, given in VAR=value format.
        default: ''
        required: false
        type: string
    outputs:
      appVersion:
        description: App version from package.json
        value: ${{ jobs.build-and-test.outputs.appVersion }}

jobs:
  build-and-test:
    name: ${{ inputs.jobName }}
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      appVersion: ${{ steps.version-from-package-json.outputs.current-version }}
    steps:
      - # https://github.com/actions/checkout v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ inputs.ref }}

      - uses: cloudbeds/workflows/.github/actions/npm-install@main

      - name: Build
        run: |
          for envVar in "${{ inputs.envVars }}"; do
            if [[ -n "$envVar" ]]; then export $envVar; fi
          done
          npm run build

      # In this workflow testing should happen after Build step
      # e.g. for case when remote types are downloaded with webpack
      - name: Lint
        run: |
          npm run lint --if-present
          npm run lint:ts --if-present

      - name: Test
        run: npm test --if-present

      - id: version-from-package-json
        # https://github.com/martinbeentjes/npm-get-version-action v1.2.3
        uses: martinbeentjes/npm-get-version-action@f9202ed69764f06546b2313b263136639df8e51e

      - name: Writing build info
        run: |
          SHA=$(git rev-parse HEAD)
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "{
            \"sha\": \"$SHA\",
            \"shaShort\": \"$SHA_SHORT\",
            \"version\": \"${{ steps.version-from-package-json.outputs.current-version }}\",
            \"viewAction\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\",
            \"viewRepo\": \"https://github.com/${{ github.repository }}/tree/$SHA\",
            \"viewCommitHistory\": \"https://github.com/${{ github.repository }}/commits/$SHA\",
            \"viewLastCommit\": \"https://github.com/${{ github.repository }}/commit/$SHA\"
          }" > ${{ inputs.artifactPath }}/build-info.json
          cat ${{ inputs.artifactPath }}/build-info.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
