# Generic workflow to lint, build, test and publish an npm package
# Output is expected to be in "dist" folder
# Suitable for cases when testing should be done on the build artifact

name: Build, Test and Publish npm package

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GH_TOKEN:
        required: true

jobs:
  test-build-release:
    name: Lint, Build, Test, Publish
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Initialize npm cache
        uses: actions/setup-node@v2
        with:
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm config set audit=false fund=false
          npm ci

      - name: Lint
        run: |
          npm run lint --if-present
          npm run lint:ts --if-present

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test --if-present

      - name: Create config file for Semantic Release
        run: |
          [ -f .releaserc ] || cat << EOF > .releaserc
          {
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              "@semantic-release/npm",
              "@semantic-release/github",
              "@semantic-release/git"
            ]
          }
          EOF

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
