# Generic workflow for a push event
# It should be used for all branches except `main` which should use the `*-release` workflow

name: Lint, Test and Build

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: The type of runner to use
        required: false
        default: x8-core
        type: string

jobs:
  lint:
    name: Lint
    runs-on: x2-4core
    steps:
      - name: Lint
        uses: cloudbeds/workflows/.github/actions/npm-install-lint@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: Test
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Test
        uses: cloudbeds/workflows/.github/actions/npm-install-test@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Build
        uses: cloudbeds/workflows/.github/actions/npm-install-build@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
