# Generic workflow to lint, test, build and publish an npm package

name: Test, Build and Publish npm package

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      # deprecated, replaced by permissions, must be removed after updating workflows that depended on this
      CB_CI_WORKFLOW_TOKEN:
        required: false
    inputs:
      runner:
        description: The type of runner to use for build and test jobs
        required: false
        default: ubuntu-latest
        type: string
      artifactPath:
        description: Destination path for the downloaded build artifact
        required: false
        default: dist
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: cloudbeds/workflows/.github/actions/npm-install-lint@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: Test
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: cloudbeds/workflows/.github/actions/npm-install-test@main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: cloudbeds/workflows/.github/actions/npm-install-build@main
        with:
          artifactPath: ${{ inputs.artifactPath }}
          withoutCoverage: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    name: Publish to NPM 🚀
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    permissions:
      contents: write
    steps:
      - name: Semantic Release
        uses: cloudbeds/workflows/.github/actions/semantic-release@main
        with:
          artifactPath: ${{ inputs.artifactPath }}
          publishToNpm: true
          GITHUB_TOKEN: ${{ secrets.CB_CI_WORKFLOW_TOKEN || secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
