# Generic workflow for a push event
# It should be used for all branches except `main` which should use the `*-release` workflow

name: Lint, Test and Build

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: cloudbeds/workflows/.github/actions/lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: cloudbeds/workflows/.github/actions/test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: cloudbeds/workflows/.github/actions/build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
